#!/bin/bash
# This should be exported from interactive shell.
# Those exports are for launching by hands, not for scripts.

function pipes()
{
	~/.config/shell/scripts/fun/pipes.sh -p3 -r6000
}

function invaiders()
{
	~/.config/shell/scripts/fun/invaiders.sh
}

function mount_smb()
{
	mkdir -p /tmp/samba/
	smbnetfs -o direct_io,readdir_ino /tmp/samba/ ||		\
		echo "Can't mount \`smbnetfs\`, error: $?"
}

# thanks, reddit
function mkcd()
{
	mkdir -p "$1" && cd "$1"
}

function mirror()
{
	mplayer -vf mirror -v tv:// -tv device=/dev/video0:driver=v4l2
}

source ~/.config/shell/scripts/qemu/aarch64_vm
source ~/.config/shell/scripts/qemu/x86_64_vm
