#!/bin/bash

# XXX: Maybe I shouldn't have it here as many parameters
#      maybe changed on needs. So use virsh with templates
#      or something alike.
function qemu_x86_64_debug()
{
	local QEMU_BIN="qemu-system-x86_64"
	local KERNEL_LOCATION="$(echo ~)/kernel/linux/arch/x86_64/boot"
	local KERNEL="bzImage"
	local DISK_LOCATION="/mnt/hdd/libvirt/images"
	local DISK="x86_64-fedora-24.img"
	#local DISK="x86_64-debian-x32.qcow2"
	local CMDLINE="root=/dev/sda3 rw console=ttyS0 earlyprintk=serial,ttyS0,115200 vsyscall=none"
	#local CMDLINE="root=/dev/sda1 rw console=ttyS0 earlyprintk=serial,ttyS0,115200"

	$QEMU_BIN -kernel "$KERNEL_LOCATION/$KERNEL"	\
		-hda "$DISK_LOCATION/$DISK"		\
		-append "$CMDLINE"			\
		-boot c					\
		-m 1024					\
		-localtime				\
		-name "debug_vm_x86"			\
		-net nic -net user			\
		-nographic				\
		-smp cpus=4				\
		-enable-kvm				\
		-gdb tcp::1235				\
		$@
}
