#!/bin/bash
# This should be included from bash scripts

NODE_NAME=$(cat ~/.config/.node_name)
NODE_PATH=~/.config/_node/${NODE_NAME}

function set_wallpaper()
{
	feh --bg-max "$1"
}

function set_wallpaper_two_monitors()
{
	convert -crop '50%x100%' +repage $1 $1
	first="${1%.*}-0.${1#*.}"
	second="${1%.*}-1.${1#*.}"
	feh --bg-scale "$first" --bg-scale "$second"
	rm "$first" "$second"
}

function pipes()
{
	~/code/scripts/pipes.sh -p3 -r6000
}

function invaiders()
{
	~/code/scripts/invaiders.sh
}

function mount_smb()
{
	mkdir -p /tmp/samba/
	smbnetfs -o direct_io,readdir_ino /tmp/samba/
}

