#!/bin/bash
# This may be included from any bash scripts.
# May be also usefull for interactive shell.
# Shouldn't content anything heavy and may be included
# multiply times.

NODE_NAME=$(cat ~/.config/.node_name)
NODE_PATH=~/.config/_node/${NODE_NAME}

[[ -f ~/.config/shell/utils ]] &&
	source ~/.config/shell/utils

source ~/.config/shell/qemu/*
