#!/bin/bash
# This should be included from bash scripts

# TODO: remove it
MACHINE_NAME=$(uname -n)
NOTEBOOK_NAME=jimi

NODE_NAME=$(cat ~/.config/.node_name)
NODE_PATH=~/.config/_node/${NODE_NAME}

if [[ "${MACHINE_NAME}" == "${NOTEBOOK_NAME}" ]]
then
function set_wallpaper()
{
	hsetroot -fill "$1"
}
else
function set_wallpaper()
{
	convert -crop '50%x100%' +repage $1 $1
	first="${1%.*}-0.${1#*.}"
	second="${1%.*}-1.${1#*.}"
	feh --bg-scale "$first" --bg-scale "$second"
	rm "$first" "$second"
}
fi

function pipes()
{
	~/code/scripts/pipes.sh -p3 -r6000
}

function invaiders()
{
	~/code/scripts/invaiders.sh
}

function mount_smb()
{
	mkdir -p /tmp/samba/
	smbnetfs -o direct_io,readdir_ino /tmp/samba/
}

