#!/bin/bash
# Those functions may be usefull in interactive shell and
# in other configs/scripts/daemons.

function set_wallpaper()
{
	feh --bg-max "$1"
}

function set_wallpaper_two_monitors()
{
	convert -crop '50%x100%' +repage $1 $1
	first="${1%.*}-0.${1#*.}"
	second="${1%.*}-1.${1#*.}"
	feh --bg-scale "$first" --bg-scale "$second"
	rm "$first" "$second"
}

