#!/bin/bash
# Those functions may be usefull in interactive shell and
# in other configs/scripts/daemons.

function patches_subj()
{
	grep Subject -R "$1" | sed 's/.*Subject: \(.*\)/\1/g'
}

function pipes()
{
	~/.config/shell/fun/pipes.sh -p3 -r6000
}

function invaiders()
{
	~/.config/shell/fun/invaiders.sh
}

function mount_smb()
{
	mkdir -p /tmp/samba/
	smbnetfs -o direct_io,readdir_ino /tmp/samba/ ||		\
		echo "Can't mount \`smbnetfs\`, error: $?"
}

# thanks, reddit
function mkcd()
{
	mkdir -p "$1" && cd "$1"
}

function mirror()
{
	mplayer -vf mirror -v tv:// -tv device=/dev/video0:driver=v4l2
}

